# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a033acfc32dc5264d8d08a2e1329dd82a0aee1110ae42929aba30b13e59a22f038bbcddc942be6048ea1344c0a3dc3543e362fbf5ee99a4f0a3e7cdf4aadb26

test:
  secret_key_base: a5123b06189bf98a6e7bc7f719c9bf49c79b2d1d3a7408b8add08bc54c457bcdddd9c52253aa10bb675fb02cdffae680043fda9b6d9915a03128f9c253297a01

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
